### ISSUE TITLE
Improve image size

### ISSUE THREAD

**Issue by TheAssassin** [Nitrux/nitrux-docker-image#6]
There should be a couple of common cleanup commands in the `RUN` command.

  - `apt-get clean`
  - `rm -rf /var/cache/apt`
  - ...

**Comment by luis-lavaire** [comment]
The image is still big (currently 487 MB). The packages that are installed must be inspected and, if possible, replaced by others; smaller and able to give the same functionality.

**Comment by TheAssassin** [comment]
500M isn't too large, considering that Qt is installed in there. Also, base images don't need to be super tiny.

But, as you say, it might actually make sense to review the packages.
